<a href="https://colab.research.google.com/github/sayaliKutwal/XDaysOfPytorch/blob/master/Tutorials/1_1_Deep_Learning_with_PyTorch_A_60_Minute_Blitz_What_is_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Deep Learning with PyTorch: A 60 Minute Blitz**

*   What is pytorch?
*   Autograd: Automatic Diifferentiation
*   Neural Networks
*   Training a Classifier 
*   Data Parallelisms



# **1. What is Pytorch?**

Tensors are numpy nd arrays which can be used on GPUs. 


In [0]:
from __future__ import print_function
import torch

x = torch.empty(5, 3)
x

tensor([[1.4474e-35, 0.0000e+00, 4.4842e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [2.1864e+23, 6.5261e-10, 1.3517e+22],
        [3.3734e-06, 5.2946e-08, 1.0606e-08],
        [3.3234e-09, 2.7599e-06, 0.0000e+00]])

NOTE

An uninitialized matrix is declared, but does not contain definite known values before it is used. When an uninitialized matrix is created, whatever values were in the allocated memory at the time will appear as the initial values.

Construct randomly initialised matrix.

In [0]:
x = torch.rand(3, 4)
x

tensor([[0.1048, 0.1689, 0.7784, 0.5388],
        [0.5284, 0.4600, 0.2093, 0.6075],
        [0.5687, 0.1655, 0.2409, 0.8679]])

COnstruch a matrix filled with zeors and data data type long.

In [0]:
x = torch.zeros(4, 2, dtype=torch.long)
x

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])

Construct a tensor directly from data

In [0]:
x = torch.tensor([32, 212.4])
x

tensor([ 32.0000, 212.4000])

Create a tensor based on a existing tensor.

In [0]:
x = x.new_ones(3, 2, dtype = torch.long) # converts x into 3*2 matrix with defined data type
                                         # new_* method take in sizes
x

tensor([[1, 1],
        [1, 1],
        [1, 1]])

In [0]:
x = torch.randn_like(x, dtype=torch.float)  # overrides datatype, can use rand_like
x

tensor([[ 0.0683, -1.1303],
        [-0.5089, -0.6702],
        [-0.2636, -0.6439]])

In [0]:
x.size()   # print the size of x

torch.Size([3, 2])

NOTE

torch.Size is in fact a tuple, so it supports all tuple operations.

# Operations
There are multiple syntaxes for operations.

In [0]:
# Addition syntax 1
y = torch.rand(3, 2)
x + y

tensor([[ 0.8618, -0.6579],
        [ 0.4198, -0.1230],
        [ 0.2180, -0.2308]])

In [0]:
# Addition syntax 2
add = torch.add(x, y)
add

tensor([[ 0.8618, -0.6579],
        [ 0.4198, -0.1230],
        [ 0.2180, -0.2308]])

In [0]:
# Addition syntax 3
result = torch.empty(3, 2)
torch.add(x, y, out=result)
result

tensor([[ 0.8618, -0.6579],
        [ 0.4198, -0.1230],
        [ 0.2180, -0.2308]])

In [0]:
# Addition: in-place
# adds x to y
y.add_(x)
y

tensor([[ 0.8618, -0.6579],
        [ 0.4198, -0.1230],
        [ 0.2180, -0.2308]])

NOTE

Any operation that mutates a tensor in-place is post-fixed with an _. For example: x.copy__(y), x.t__(), will change x.

In [0]:
# You can use standard NumPy-like indexing with all bells and whistles!

print(x[1, :])

tensor([-0.5089, -0.6702])


Resizing: If you want to resize/reshape tensors, use torch.view

In [0]:
x = torch.randn(4, 5)
y = x.view(20)
z = x.view(20, -1) # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 5]) torch.Size([20]) torch.Size([20, 1])


If you have only one-element tensor, use .item() to get the value as a python number.

In [0]:
x = torch.rand(1)
print(x)
x.item()

tensor([0.9723])


0.9723095297813416

Continue from here https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#numpy-bridge 

# **NumPy Bridge**

In [4]:
# Converting a Torch Tensor to a Numpy array
import torch
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [6]:
# See how the numpy array changed in value
a.add_(1)
print(a)
print(b)

tensor([3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3.]


In [7]:
#  Converting numpy arraye into torch tensor

import numpy as np
a = np.ones(3)
b = torch.from_numpy(a)
np.add(a, 1,out=a)
print(a)
print(b)

[2. 2. 2.]
tensor([2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

**CUDA Tensor**
Tensors can be moved onto any device using the .to method

In [0]:
if torch.cuda.is_available():
  device = torch.device('cuda')
  y = torch.ones_like(x, device=device) 
  x = x.to(device)   # can use .to('cuda')
  z = x + y
  print(z)
  print(z.to('cpu', torch.double))